version: '3.8'
services:
  neo4j:
    container_name: neo4j
    image: neo4j:5.13.0
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_EDITION=docker_compose
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=jwt.security.*,apoc.*,gds.*
    volumes:
      - neo4jdata:/data
      - neo4jlogs:/logs
      - neo4jconf:/conf
      - neo4jplugins:/plugins
      - neo4jlicenses:/licenses
      - neo4jimport:/neo4jimport

volumes:
  neo4jdata:
  neo4jlogs:
  neo4jconf:
  neo4jplugins:
  neo4jlicenses:
  neo4jimport:
